---
name: Run Script
on:
  push:
    branches: [ main ]
    paths:
      - Template/**

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: execute script
      run: |
        sudo su
        python main.yml
      
